### ISSUE TITLE
解析 ClashMeta 配置中的 VMESS-WS 时出现 bug，对旧版 Clash 配置中 ws 传输层配置的兼容性支持

### ISSUE THREAD

**Issue by QCEnjoyLL** [kobe-koto/EdgeSub#11]
![image](https://github.com/user-attachments/assets/4e90d480-8264-4d0f-9de6-ae687ff48a11)
节点数量多了转换后就会报错，如上图

**Comment by QCEnjoyLL** [comment]
试了下300个节点没问题，350个就不得行了
无法导入clash
![image](https://github.com/user-attachments/assets/5c25d843-7521-4bd8-a9b4-f60335aa9340)
打开生成的链接就是第一条的错误
最后，pages的日志是在哪里看？

**Comment by kobe-koto** [comment]
![image](https://github.com/user-attachments/assets/c04a7646-9030-47e4-904d-5b343280dfa6)

**Comment by QCEnjoyLL** [comment]
![image](https://github.com/user-attachments/assets/e240bd0d-d4b2-4f7c-99bd-82d43804e0a9)
```
{
  "truncated": false,
  "executionModel": "stateless",
  "outcome": "exception",
  "scriptVersion": {
    "id": "5f61e6d5-1c3f-4ee2-ab04-152b34156e9d"
  },
  "scriptName": "pages-worker--3913429-production",
  "diagnosticsChannelEvents": [],
  "exceptions": [
    {
      "stack": "    at __genTransportWS (functionsWorker-0.054051107044506.js:3504:54)\n    at Dumper.vmess (functionsWorker-0.054051107044506.js:3682:22)\n    at functionsWorker-0.054051107044506.js:4132:61\n    at Array.map (<anonymous>)\n    at getClashMetaConfig (functionsWorker-0.054051107044506.js:4132:33)\n    at async onRequest4 (functionsWorker-0.054051107044506.js:4232:31)\n    at async Object.next (functionsWorker-0.054051107044506.js:5326:26)\n    at async PerformanceCounting (functionsWorker-0.054051107044506.js:4836:20)\n    at async Object.next (functionsWorker-0.054051107044506.js:5326:26)\n    at async RequestInfo (functionsWorker-0.054051107044506.js:4832:10)",
      "name": "TypeError",
      "message": "Cannot read properties of undefined (reading 'ed')",
      "timestamp": 1731999276055
    }
  ],
  "logs": [
    {
      "message": [
        "[Main] Processing request..."
      ],
      "level": "info",
      "timestamp": 1731999275842
    },
    {
      "message": [
        "[Main] Request type: /sub/clash-meta"
      ],
      "level": "info",
      "timestamp": 1731999275842
    },
    {
      "message": [
        "[Fetch Sub Data] Job started"
      ],
      "level": "info",
      "timestamp": 1731999275842
    },
    {
      "message": [
        "[Fetch Sub Data] isShowHost: false"
      ],
      "level": "info",
      "timestamp": 1731999275842
    },
    {
      "message": [
        "[Fetch Sub Data] Fetching 1/1"
      ],
      "level": "info",
      "timestamp": 1731999275842
    },
    {
      "message": [
        "[Parser: Clash Meta] [WARN] undefined is not supported to parse, ignoring..."
      ],
      "level": "warn",
      "timestamp": 1731999276032
    },
    {
      "message": [
        "[Fetch Sub Data] Job done, wasting 190ms."
      ],
      "level": "info",
      "timestamp": 1731999276032
    },
    {
      "message": [
        "[Remote Config Reader] Inputed remote config type: ini"
      ],
      "level": "info",
      "timestamp": 1731999276032
    },
    {
      "message": [
        "[Remote Config Reader] Job started"
      ],
      "level": "info",
      "timestamp": 1731999276032
    },
    {
      "message": [
        "[Remote Config Reader] Job done, wasting 0ms"
      ],
      "level": "info",
      "timestamp": 1731999276032
    }
  ],
  "eventTimestamp": 1731999275842,
  "event": {
    "request": {
      "url": "https://sub.nloln.cn/sub/clash-meta?url=https%3A%2F%2Fraw.githubusercontent.com%2FQCEnjoyLL%2Ftest%2Frefs%2Fheads%2Fmaster%2F400.yaml&remote_config=__DEFAULT__&udp=true&show_host=false&forced_ws0rtt=false",
      "method": "GET",
      "headers": {
        "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
        "accept-encoding": "gzip, br",
        "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
        "cache-control": "max-age=0",
        "cf-connecting-ip": "111.10.212.62",
        "cf-connecting-o2o": "1",
        "cf-ipcountry": "CN",
        "cf-ray": "8e4e4a31e8cd17de",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "connection": "Keep-Alive",
        "cookie": "REDACTED",
        "host": "sub.nloln.cn",
        "priority": "u=0, i",
        "sec-ch-ua": "\"Microsoft Edge\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"Windows\"",
        "sec-fetch-dest": "document",
        "sec-fetch-mode": "navigate",
        "sec-fetch-site": "none",
        "sec-fetch-user": "?1",
        "upgrade-insecure-requests": "1",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0",
        "x-forwarded-for": "111.10.212.62",
        "x-forwarded-proto": "https",
        "x-real-ip": "111.10.212.62"
      },
      "cf": {
        "longitude": "106.55770",
        "httpProtocol": "HTTP/2",
        "tlsCipher": "AEAD-AES128-GCM-SHA256",
        "continent": "AS",
        "asn": 9808,
        "clientAcceptEncoding": "gzip",
        "country": "CN",
        "verifiedBotCategory": "",
        "tlsClientAuth": {
          "certIssuerDNLegacy": "",
          "certIssuerSKI": "",
          "certSubjectDNRFC2253": "",
          "certSubjectDNLegacy": "",
          "certFingerprintSHA256": "",
          "certNotBefore": "",
          "certSKI": "",
          "certSerial": "",
          "certIssuerDN": "",
          "certVerified": "NONE",
          "certNotAfter": "",
          "certSubjectDN": "",
          "certPresented": "0",
          "certRevoked": "0",
          "certIssuerSerial": "",
          "certIssuerDNRFC2253": "",
          "certFingerprintSHA1": ""
        },
        "tlsClientHelloLength": "",
        "tlsVersion": "TLSv1.3",
        "city": "Chongqing",
        "timezone": "Asia/Shanghai",
        "tlsClientExtensionsSha1": "",
        "region": "Chongqing",
        "edgeRequestKeepAliveStatus": 1,
        "requestPriority": "weight=256;exclusive=1",
        "latitude": "29.56890",
        "tlsClientRandom": "",
        "regionCode": "CQ",
        "asOrganization": "China Mobile",
        "colo": "SJC",
        "pagesHostName": "edgesub-cax.pages.dev",
        "botManagement": {
          "corporateProxy": false,
          "verifiedBot": false,
          "jsDetection": {
            "passed": false
          },
          "staticResource": false,
          "detectionIds": {},
          "score": 99
        }
      }
    },
    "response": {
      "status": 500
    }
  },
  "id": 1
}
```

**Comment by kobe-koto** [comment]
知道问题所在了，只能周末修，目前没时间。

上传日志记得脱敏啊哥，，不过也好，顺便把测试数据提供了

**Comment by QCEnjoyLL** [comment]
节点都是别的地方公开的，没得关系

**Comment by QCEnjoyLL** [comment]
刚试了下，标准和非标准的都没问题了

**Comment by kobe-koto** [comment]
> 刚试了下，标准和非标准的都没问题了

“非标准”恐是我的错误用词，刚刚发现这种写法仅存在于旧版 clash 配置中，现已弃用。

周末再考虑兼容性问题吧。

**Comment by kobe-koto** [comment]
fixed
